/**
 * CEO Monthly PDF Report Generator
 * Uses browser-native printing as a reliable, zero-dependency PDF solution.
 * For a more polished PDF, install jsPDF + jspdf-autotable.
 */

const formatMonth = () => {
  const now = new Date();
  return now.toLocaleDateString(undefined, { month: "long", year: "numeric" });
};

const buildKpiRow = (label, value) =>
  `<tr><td style="padding:8px 16px;font-weight:600;border-bottom:1px solid #e0e0e0">${label}</td>
   <td style="padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0">${value}</td></tr>`;

export function exportCeoPdf({ trends, monthly }) {
  const kpi = trends?.kpi || {};
  const cur = monthly?.current || {};

  const html = `
    <html>
    <head>
      <title>CEO Monthly Report — ${formatMonth()}</title>
      <style>
        body { font-family: 'Inter', 'Segoe UI', Arial, sans-serif; color: #1a1a1a; padding: 40px; }
        h1 { color: #0a1929; margin-bottom: 4px; }
        h2 { color: #1565c0; margin-top: 32px; border-bottom: 2px solid #1565c0; padding-bottom: 6px; }
        .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
        th { background: #0a1929; color: #fff; padding: 10px 16px; text-align: left; }
        td { padding: 8px 16px; }
        .section { margin-bottom: 24px; }
        .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; }
      </style>
    </head>
    <body>
      <h1>📊 NEBSAM — CEO Monthly Report</h1>
      <div class="subtitle">${formatMonth()} | Generated ${new Date().toLocaleString()}</div>

      <h2>Executive KPIs</h2>
      <table>
        <thead><tr><th>Metric</th><th style="text-align:right">Value</th></tr></thead>
        <tbody>
          ${buildKpiRow("Total Sales This Month", trends?.thisMonthSales ?? "—")}
          ${buildKpiRow("Growth vs Last Month", trends?.pctVsLastMonth != null ? `${trends.pctVsLastMonth.toFixed(1)}%` : "—")}
          ${buildKpiRow("Gov Installs", kpi.govInstalls ?? "—")}
          ${buildKpiRow("Gov Renewals", kpi.govRenewals ?? "—")}
          ${buildKpiRow("Fuel Installs", kpi.fuelInstalls ?? "—")}
          ${buildKpiRow("Fuel Renewals", kpi.fuelRenewals ?? "—")}
          ${buildKpiRow("Radio Sales", kpi.radioSales ?? "—")}
          ${buildKpiRow("Radio Renewals", kpi.radioRenewals ?? "—")}
          ${buildKpiRow("Tracking Installs", kpi.trackingInstalls ?? "—")}
          ${buildKpiRow("Tracking Renewals", kpi.trackingRenewals ?? "—")}
          ${buildKpiRow("Top Showroom", kpi.trackingTopShowroom ?? "—")}
        </tbody>
      </table>

      <h2>Department Performance — Current Month</h2>
      <table>
        <thead><tr><th>Department</th><th style="text-align:right">Installs/Sales</th><th style="text-align:right">Renewals</th></tr></thead>
        <tbody>
          ${buildKpiRow("Speed Governor</td><td style='padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0'>" + (cur.gov?.installs ?? 0), cur.gov?.renewals ?? 0)}
          ${buildKpiRow("Tracking</td><td style='padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0'>" + (cur.tracking?.installs ?? 0), cur.tracking?.renewals ?? 0)}
          ${buildKpiRow("Fuel</td><td style='padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0'>" + (cur.fuel?.installs ?? 0), cur.fuel?.renewals ?? 0)}
          ${buildKpiRow("Radio</td><td style='padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0'>" + (cur.radio?.sales ?? 0), cur.radio?.renewals ?? 0)}
          ${buildKpiRow("Video Telematics</td><td style='padding:8px 16px;text-align:right;border-bottom:1px solid #e0e0e0'>" + (cur.vtel?.installs ?? 0), cur.vtel?.renewals ?? 0)}
        </tbody>
      </table>

      <div class="footer">
        NEBSAM Executive Report — Confidential | Auto-generated by CEO Dashboard
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 500);
}